apiVersion: apps/v1
kind: Deployment
metadata:
  name: fancy-counter
  labels:
    app: fancy-counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fancy-counter
  template:
    metadata:
      labels:
        app: fancy-counter
    spec:
      containers:
      - name: fancy-counter
        image: nginx:latest   # (temporary test image)
        ports:
        - containerPort: 80
