apiVersion: v1
kind: Service
metadata:
  name: fancy-counter-service
spec:
  selector:
    app: fancy-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
